import pandas as pd
import binascii
import os

# --- CONFIGURATION ---
INPUT_CSV = 'key_generation_data.csv'
OUTPUT_BIN_FILE = 'keys_group_E_for_NIST.bin'
MODE_TO_EXTRACT = 'CSPRNG_ROBUST'

def prepare_data_for_nist():
    """
    Loads key data from CSV, filters for Group E (CSPRNG_ROBUST mode), 
    and concatenates the keys into a single binary file for NIST testing.
    """
    if not os.path.exists(INPUT_CSV):
        print(f"Error: Input file '{INPUT_CSV}' not found.")
        print("Please ensure the CSV file generated by the key generator script is in the same directory.")
        return

    try:
        # Load the CSV file
        df = pd.read_csv(INPUT_CSV)
        
        # Filter the DataFrame to include only keys generated in the robust mode (Group E)
        group_e_keys = df[df['KDF Mode'] == MODE_TO_EXTRACT]
        
        if group_e_keys.empty:
            print(f"Error: No keys found with KDF Mode '{MODE_TO_EXTRACT}'.")
            print("Please ensure you collected data for Group E by covering the camera and pressing 'm'.")
            return

        print(f"Successfully loaded {len(df)} keys from CSV.")
        print(f"Found {len(group_e_keys)} keys for Group E: {MODE_TO_EXTRACT}")

        # Extract the hexadecimal key strings
        # NOTE: The column name must exactly match the header in your CSV file.
        # Assuming the column is 'Quantum Key (Hex)' based on the stable script.
        hex_keys = group_e_keys['Quantum Key (Hex)'].tolist()

        # Concatenate all hex strings into one large string
        all_hex_data = "".join(hex_keys)
        
        # Convert the continuous hex string into raw binary data
        try:
            binary_data = binascii.unhexlify(all_hex_data)
        except binascii.Error as e:
            print(f"Critical Error during hex-to-binary conversion: {e}")
            print("Check if all key strings in the 'Quantum Key (Hex)' column are valid, even-length hexadecimal.")
            return

        # Write the binary data to the output file
        with open(OUTPUT_BIN_FILE, 'wb') as f:
            f.write(binary_data)
        
        # Final output summary
        total_bytes = len(binary_data)
        total_bits = total_bytes * 8
        
        print("\n--- Success ---")
        print(f"Output File: {OUTPUT_BIN_FILE}")
        print(f"Total Bytes (Keys) Written: {total_bytes}")
        print(f"Total Bits Written: {total_bits} (The NIST test suite requires millions of bits!)")
        print(f"\nYour data is now ready. Run the NIST tests on '{OUTPUT_BIN_FILE}'.")

    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == '__main__':
    prepare_data_for_nist()